### ISSUE TITLE
airtable-schema-extractor errors

### ISSUE THREAD

**Issue by kostasb** [xataio/migrator#3]
The script airtable-schema-extractor fails in the console of `Airtable API for "mybase"` page in airtable's `/api/docs`.

Perhaps the content of the page has changed.

e.g. airtable-schema-extractor script section:

```
data.source.apiKey = document
  .querySelector("[data-api-key]")
  .getAttribute("data-api-key");
```

**Errors**

Chrome:
```
Uncaught TypeError: Cannot read properties of null (reading 'getAttribute')
```

Firefox:
```
Uncaught TypeError: document.querySelector(...) is null
```

**Comment by fabien0102** [comment]
Nice catch, the `apiKey` is not part of the documentation anymore, this fixed by f1b8065948bed8
